# Langeland_Stephanie
Stephanie Langeland's (UNI: sal2209) assignments for Modern Data Structures (Fall 2017)

`EconFiData` Package Folder:

File/Folder:  Description 

`vignettes` folder:  Please use these vignette files as a guide to re-perform the functions
created in this package.  The vignettes should be reviewed in the following order:

  1) `get-historical-dates-vignette.Rmd`: Corresponds to the 
  `EconFiData/R/get_historical_dates.R` file.
  
  2) `get-series-obs-vignette.Rmd` file.  Corresponds to the 
  `EconFiData/R/get_historical_dates.R` file.
  
  3) `all-yf-functions-vignette.Rmd` file.  Corresponds to the 
  following files: 
  
    * `EconFiData/R/get_yf_url.R`
    
    * `EconFiData/R/scroll_yf.R`
    
    * `EconFiData/R/parse_yf.R`
    
    * `EconFiData/R/clean_yf_data.R`

`R` folder: Contains all `.R` script files.  When these files were documented
via `document()`, the `.Rd` files in the `man` folder were created.

`data` folder: The data sets included in the package.  Refer to the 
`/EconFiData/R/data.R` file for details. 

`LICENSES` file: Contains the year when the package was last updated and
copyright holder's name.

`DESCRIPTION` file: Contains relevant package information.

`EconFiData.Rproj` file: EconFiData package file.

`NAMESPACE` file: Contains the exported function names.

